BEGIN;

ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_adjustment_factors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.house_lineup_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contest_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.currency_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shop_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projection_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.h2h_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entry_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.h2h_lineup_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_archetypes_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_per100_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_positions_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_stats_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_game_logs_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.targeted_plays_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ownership_projections_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_salaries_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.injury_alerts_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dfs_players_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prop_recommendations_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dva_stats_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.archetype_profiles_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_defense_shot_zones_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_play_types_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_headshots_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_odds_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_measurements_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matchup_history_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.archetype_matchup_profiles_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_shot_zones_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_shot_creation_live ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_hustle_stats_live ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_read_player_archetypes_live" ON public.player_archetypes_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_player_per100_live" ON public.player_per100_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_player_positions_live" ON public.player_positions_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_player_stats_live" ON public.player_stats_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_player_game_logs_live" ON public.player_game_logs_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_targeted_plays_live" ON public.targeted_plays_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_ownership_projections_live" ON public.ownership_projections_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_player_salaries_live" ON public.player_salaries_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_injury_alerts_live" ON public.injury_alerts_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_dfs_players_live" ON public.dfs_players_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_prop_recommendations_live" ON public.prop_recommendations_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_dva_stats_live" ON public.dva_stats_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_archetype_profiles_live" ON public.archetype_profiles_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_team_defense_shot_zones_live" ON public.team_defense_shot_zones_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_team_play_types_live" ON public.team_play_types_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_player_headshots_live" ON public.player_headshots_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_game_odds_live" ON public.game_odds_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_player_measurements_live" ON public.player_measurements_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_matchup_history_live" ON public.matchup_history_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_archetype_matchup_profiles_live" ON public.archetype_matchup_profiles_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_player_shot_zones_live" ON public.player_shot_zones_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_player_shot_creation_live" ON public.player_shot_creation_live FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_player_hustle_stats_live" ON public.player_hustle_stats_live FOR SELECT TO anon USING (true);

CREATE POLICY "anon_read_shop_items" ON public.shop_items FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_achievements" ON public.achievements FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_leaderboard_cache" ON public.leaderboard_cache FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_contests" ON public.contests FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_house_lineup_players" ON public.house_lineup_players FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_projection_snapshots" ON public.projection_snapshots FOR SELECT TO anon USING (true);

COMMIT;
